controllers:
  - skrift.controllers.auth:AuthController
  - skrift.controllers.web:WebController

db:
  url: $DATABASE_URL
  pool_size: 5
  pool_overflow: 10
  pool_timeout: 30
  echo: false

auth:
  redirect_base_url: $OAUTH_REDIRECT_BASE_URL
  providers:
    google:
      client_id: $GOOGLE_CLIENT_ID
      client_secret: $GOOGLE_CLIENT_SECRET
      scopes:
        - openid
        - email
        - profile
