"""Hashing for OAuth2 ``client_secret`` values stored at rest.

Client secrets are 256-bit random tokens generated by
:func:`secrets.token_urlsafe`, so slow-hash resistance (bcrypt/argon2) adds
no security against brute force — you cannot search 256 bits regardless of
hash speed. We use salted SHA-256 for per-record uniqueness and sub-ms
verification on the OAuth2 token endpoint.

Storage format: ``"sha256$<salt_b64>$<hash_b64>"``. The algorithm prefix
lets a future migration to bcrypt/argon2 coexist with existing records
(``verify_client_secret`` would branch on the prefix). Unprefixed values
are rejected — the alembic migration is the single source of re-hashing
legacy plaintext rows.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import secrets as _secrets

_ALGO = "sha256"
_PREFIX = f"{_ALGO}$"
_SALT_BYTES = 16


def _b64e(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).rstrip(b"=").decode("ascii")


def _b64d(value: str) -> bytes:
    padding = "=" * (-len(value) % 4)
    return base64.urlsafe_b64decode(value + padding)


def _digest(plaintext: str, salt: bytes) -> bytes:
    return hashlib.sha256(salt + plaintext.encode("utf-8")).digest()


def hash_client_secret(plaintext: str) -> str:
    """Return a storage-form ``"sha256$<salt>$<hash>"`` string."""
    if not plaintext:
        raise ValueError("client_secret must be non-empty")
    salt = _secrets.token_bytes(_SALT_BYTES)
    digest = _digest(plaintext, salt)
    return f"{_PREFIX}{_b64e(salt)}${_b64e(digest)}"


def verify_client_secret(submitted: str, stored: str) -> bool:
    """Constant-time verify a submitted plaintext against a stored hash.

    Returns ``False`` for empty, malformed, or legacy-unprefixed stored
    values so the only way a client authenticates is through a row that
    has been migrated to the current format.
    """
    if not submitted or not stored:
        return False
    if not stored.startswith(_PREFIX):
        return False
    parts = stored.split("$")
    if len(parts) != 3:
        return False
    _, salt_b64, hash_b64 = parts
    try:
        salt = _b64d(salt_b64)
        expected = _b64d(hash_b64)
    except (ValueError, base64.binascii.Error):
        return False
    computed = _digest(submitted, salt)
    return hmac.compare_digest(computed, expected)


def is_hashed(stored: str) -> bool:
    """Return True when ``stored`` is in the hashed storage format.

    Used by the alembic upgrade hook to skip already-hashed rows so the
    migration is idempotent.
    """
    return bool(stored) and stored.startswith(_PREFIX)
