models:
  - twitter.models

controllers:
  - twitter.controllers.feed:FeedController
  - twitter.controllers.tweet:TweetController
  - twitter.controllers.profile:ProfileController
  - twitter.controllers.admin:TwitterAdminController
  - skrift.controllers.auth:AuthController
  - skrift.admin.controller:AdminController
middleware:
  # Example: Custom middleware (uncomment to use)
  # - myapp.middleware:create_logging_middleware
  # - factory: myapp.middleware:create_rate_limit_middleware
  #   kwargs:
  #     requests_per_minute: 100
db:
  url: $DATABASE_URL
  pool_size: 5
  pool_overflow: 10
  pool_timeout: 30
  echo: false
auth:
  redirect_base_url: http://localhost:8080
  providers:
    google:
      client_id: $GOOGLE_CLIENT_ID
      client_secret: $GOOGLE_CLIENT_SECRET
      scopes:
        - openid
        - email
        - profile
